stm32_nucleo_f303re_driver:
  ros__parameters:
    port: "/dev/ttyACM0"
    baudrate: 115200
    frequency_ms: 5
    
joy_teleop_twist_ref:
  ros__parameters:
    max_vel: 0.20
    scales: 1.0
    wheel_base: 0.2

joy_service_node:
  ros__parameters:
    joy_service: true
    arm_button: 0
    reset_button: 6


lidar_driver:
  ros__parameters:
    port: "/dev/ttyAMA0"

/burger/realsense:
  ros__parameters:
    enable_color: false
    depth_module.depth_profile: "640x480x30"
    pointcloud.enable: false
    decimation_filter.enable: true
    align_depth.enable: false
    enable_sync: false
    enable_gyro: false
    enable_accel: false
    pointcloud.allow_no_texture_points: false

