stm32_nucleo_f303re_driver:
  ros__parameters:
    port: "/dev/ttyACM0"
    baudrate: 115200
    frequency_ms: 5
    
joy_teleop_twist_ref:
  ros__parameters:
    max_vel: 0.463
    scales: 0.0
    wheel_base: 0.2

joy_service_node:
  ros__parameters:
    arm_service: true
    arm_button: 0


lidar_driver:
  ros__parameters:
    port: "/dev/ttyAMA0"

